from django.db import models

# Create your models here.


class Task(models.Model):
    first_name = models.CharField(max_length=30)
    pas_name = models.CharField(max_length=30)



'''CREATE TABLE myapp_person (
    "id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "first_name" varchar(30) NOT NULL,
    "last_name" varchar(30) NOT NULL
);'''




